### ISSUE TITLE
Having an issue trying to retrieve data from Huncwot server.

### ISSUE THREAD

**Issue by inc16sec** [huncwotjs/huncwot#50]
Hello there. So I've been playing around with this amazing library and everything seemed to be going so well but the it wasn't :D 

So i connected huncwot with my Neo4j db and tried to fetch some data and it works well with browser but when i try to fetch call the GET request from Flutter/emulator it gives me an error.

On the Flutter DEBUG CONSOLE it prints an HTML response (which i don't know from where did it come from) and in the Huncwot consol it prints (undefined Internal Server Error)

Here's my Neo4j query function 

`static browseUserData() {
       return session.run('MATCH (u:USER) RETURN u.display_name AS name, u.bio AS bio')
               .then((res) => {
                   return JSON.stringify(res.records, null, 3);
               })
               .catch((error) => {
                   console.error(error);
               });
    }`

And here's my Handler function from User folder i have a browse.ts file inside controller folder

`const browse: Handler = async (): Promise<any> => {
   const user = await DatabaseEvents.browseUserData();
   return OK(user);
}
`
`export = browse;`

and here's my how i try to GET the data from Flutter

`var uri = 'http://1localhost:5544/user';

    browseData() async {
       http.Response response = await http.get(uri);
       print(response.body);
  }`
 All of this works fine and as expected in a normal browser (Chrom in my case) but on Flutter it prints something else 

This is what I get.

`flutter: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title> </title>
  <style type="text/css">
    /* http://prismjs.com/download.html?themes=prism&languages=markup+css+clike+javascript&plugins=line-highlight+line-numbers+toolbar+show-language */
/**
 * prism.js default theme for JavaScript, CSS and HTML
 * Based on dabblet (http://dabblet.com)
 * @author Lea Verou
 */
code[class*="language-"],
pre[class*="language-"] {
  color: black;
  background: none;
  text-shadow: 0 1px white;
  font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;
  text-align: left;
  white-space: pre;
  word-spacing: normal;
  word-break: normal;
  word-wrap: normal;
  line-height: 1.8;
  -moz-tab-size: 4;
  -o-tab-size: 4;
  tab-size: 4;
  -webkit-hyphens: none;
  -moz-hyphens: none;
  -ms-hyphens: none;
  hyphens: none;
}
pre[class*="language-"]::-moz-selection, pre[class*="language-"] ::-moz-selection,
code[class*="language-"]::-moz-selection, code[class*="language-"] ::<…>`

And this is what is printed on huncwot consol where i've started the sever.

`┌ GET /user → undefined Internal Server Error
└ Params

  Error Cannot read property 'split' of undefined
  Explanation 
  (missing)

  Stack trace
  - parseAcceptHeader
    /usr/local/lib/node_modules/huncwot/index.js:407
  - handleRequest
    /usr/local/lib/node_modules/huncwot/index.js:301
  - RouterMiddleware
    /usr/local/lib/node_modules/huncwot/index.js:167
  - Middleware.next
    /usr/local/lib/node_modules/huncwot/index.js:45
  - undefined
    /usr/local/lib/node_modules/huncwot/index.js:48
  - CORSMiddleware
    /usr/local/lib/node_modules/huncwot/index.js:192
  - Middleware.next
    /usr/local/lib/node_modules/huncwot/index.js:45
  - Middleware.compose
    /usr/local/lib/node_modules/huncwot/index.js:54
  - Server.<anonymous>
    /usr/local/lib/node_modules/huncwot/index.js:208
  - Server.emit
    events.js:321`

P.S. I've tried with the approach of youtube where you store JSON data locally and extract it and it worked fine with flutter, but for Neo4j data, things seem to be different.

Thank you so much.
Best regards.

**Comment by zaiste** [comment]
@inc16sec Thanks for the kind words! :)

Could you try to update the Huncwot version in your `package.json` from `0.51.0` to `0.52.1`, followed by `npm install` ? It should fix it. Let me know

**Comment by inc16sec** [comment]
Hello @zaiste  I have just updated my `package.json` to `0.52.1` but I still face the same issue.

Here's what I get on huncwot terminal.

<img width="625" alt="Screenshot 2020-02-04 at 12 08 30" src="https://user-images.githubusercontent.com/54755080/73739777-29566780-4747-11ea-8d28-92be48067f9b.png">

And here's what is on Flutter Debugger.

<img width="738" alt="Screenshot 2020-02-04 at 12 10 20" src="https://user-images.githubusercontent.com/54755080/73739867-5a369c80-4747-11ea-89ad-82380d26e850.png">

I have tried to get the data from the browser and it works fine.
Thank you for your help. Much appreciated.

**Comment by inc16sec** [comment]
Apologies.. It's working now. you were right about the package version. Well, apparently it looks like I didn't update the package by changing its version from `package.json` and running `npm install`. After I've run `huncwot --version` i found that I was still using the same package `0.52.0`. But after I've run `npm update -g huncwot` it did update the package and after trying it with Flutter it worked just fine :)
I want to say thank you so much for replying and for your work and teachings on youtube which as a beginner I appreciate a lot and learn so much from (you have a way of teaching that makes the unfathomed easy to understand), I hope that you keep doing what you're doing and I hope there will be more from you soon (especially with databases).
Best regard "One of your students", with much appreciation.

**Comment by zaiste** [comment]
@inc16sec No worries! It's my fault anyway :) I'm happy I could help. Please, let me know if you had other issues. I'm trying to make the Huncwot experience as simple as possible. Sometimes it's difficult for me to present the things properly. I'd appreciate your feedback.

**Comment by inc16sec** [comment]
@zaiste  Sure thing, I'll keep working with it because so far it is the best solution I've came across. Also, do you have a "discord" or something where we can ask/look for help about huncwot ? There are a lot of things that I would like to know about but I don't think Github is the place where to put my questions.

**Comment by zaiste** [comment]
@inc16sec Here's the discord: https://discordapp.com/invite/eK6HjjG On second though, I'd prefer questions as GitHub issues so that they are searchable.
